[env:genericGD32F305]
platform = ststm32
board = genericSTM32F103RC
framework = arduino
build_src_filter = +<main.cpp> -<main.cpp_>

; --- Programming / monitor ---
upload_protocol = stlink
monitor_speed = 115200

; IMPORTANT:
; We use genericSTM32F103RC for hardware/register compatibility.
; However, the actual chip is GD32F305RCT6, so we use a custom linker script
; with 96KB of RAM.
; Standalone firmware: the complete image starts at the flash base.
board_upload.offset_address = 0x08000000
board_build.ldscript = GD32F305RC_COMBOX.ld

build_flags =
    -D HSE_VALUE=8000000U
    -D GCC_VERSION=120301
    -D GD32F305
    -D GD32F30X_HD

extra_scripts = post:generate_hex.py
